---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-mysql-config
data:
  db_url: "mysql-service"
  db_host: "localhost"
  db_user: "root"
  db_type: "MONGO"
  db_name: "contacts_app"
  mongo_url: "mongodb://mongo-service:27017"
  mongodb_host: "mongo-service"
  db_port: "27017"
  my.cnf: | # This is the configuration file for MySQL
    [mysqld]
    transaction-isolation = READ-COMMITTED

---
apiVersion: v1
kind: Service
metadata:
  name: shared-loadbalancer-service
spec:
  selector:
    app: shared-app  # Ensure your pods use this shared label
  type: LoadBalancer
  ports:
    - name: flask-contacts
      protocol: TCP
      port: 5052      # Load Balancer listens here
      targetPort: 5052  # Container port in Flask Contacts
      nodePort: 30001  # Node port for Flask Contacts
    - name: mongo-express
      protocol: TCP
      port: 8081      # Load Balancer listens here
      targetPort: 8081  # Container port in Mongo Express
      nodePort: 30002  # Node port for Mongo Express

          
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017