---
- name: Install required roles from requirements.yml
  hosts: aws_jenkins
  gather_facts: false

  tasks:
    - name: Install roles using ansible-galaxy
      ansible.builtin.shell: ansible-galaxy install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      register: galaxy_install
      changed_when: galaxy_install.stdout != ""

    - name: Debug output from ansible-galaxy
      ansible.builtin.debug:
        var: galaxy_install.stdout

- name: Deploy Dockerized Flask App from Docker Hub
  hosts: aws_jenkins
  become: true

  roles:
    - Shashkist.ansible-role-jdk-17
    - geerlingguy.jenkins
    - darkwizard242.eksctl
    - andrewrothstein.kubectl
    - Shashkist.install-aws-cli-on-UBUNTU-24
