apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-mysql-config
data:
  db_url: "mysql-service"
  db_host: "localhost"
  db_user: "root"
  db_type: "MONGO"
  db_name: "contacts_app"
  mongo_url: "mongodb://mongo-service:27017"
  mongodb_host: "mongo-service"
  db_port: "27017"
  my.cnf: | # This is the configuration file for MySQL
    [mysqld]
    transaction-isolation = READ-COMMITTED